# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ddcb44190f52162bb4f77d59ec2ddec4bb33f051237d2291c8ff1ff9f37363f3e51626e03b2809f30ed113bc351b219b5b5362f45bd42f8d10ff455320f4ded

test:
  secret_key_base: d2b1b98a8e408535e9a7a8d833bb18a0e6320144085b3afd348e2fad9a8c8dade163bf31e4934d2e8ec75e65126bc637e813ad9d3bdd3a8e4851962cff9994cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
